// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © MikerikDev

//@version=5
indicator("ATR-SB Indicator", overlay = true)


//--------------- INITIAL VARIABLES
_risk = input(defval = 1, title = "Risk (higher value = less risk)")
_atr = ta.atr(10)
_modified_atr = _risk * _atr
_src = close


//--------------- Functions that are being used
main_logic( _input ) =>
    result = 0.0

    if close > _input and close[1] > _input
        result := math.max(_input, close - _modified_atr)
    else if close < _input and close[1] < _input
        result := math.min(_input, close + _modified_atr)
    else if close > _input
        result := close - _modified_atr
    else
        result := close + _modified_atr



direction_logic( _input ) =>
    _dir = 0
    if   close[1] < _input and close > _input
        _dir := 1
    else if close[1] > _input and close < _input
        _dir := -1

//--------------- Indicator logic
_xATR = 0.0
_xATR := main_logic(_xATR[1])

_direction = 0
_direction := direction_logic(_xATR[1])


ema   = ta.ema(close,1)
above = ta.crossover(ema, _xATR)
below = ta.crossover(_xATR, ema)

barcolor( _direction == 1 or _direction == -1 ? color.yellow : na )
plot(_xATR, color = color.white, linewidth = 2)
plot(ema, color = color.blue, linewidth = 1)


//--------------- TEST FUNCTIONS

plotshape(_direction == 1, location = location.belowbar, style = shape.labelup, color = color.green, size = size.normal, text = "BUY", textcolor = color.black)
plotshape(_direction == -1, location = location.abovebar, style = shape.labeldown, color = color.red, size = size.normal, text = "SELL", textcolor = color.black)